FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin
ENV GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
ENV N8N_ENCRYPTION_KEY=Chienkh2003

EXPOSE 5678

CMD ["n8n", "start"]
